#Talar om for bundler var biblioteken vi ska anvanda finns
#kor "bundle install" i terminalen i samma mapp for att ladda ner biblioteken

source 'https://rubygems.org'

gem 'thin'
gem 'sinatra'
gem 'rerun'
gem 'sqlite3'
gem 'debug'
gem 'bcrypt'
